version: '3.8'

services:
  mysqldb:
    build:
      context: ./db
    environment:
        - MYSQL_DATABASE=$DB_NAME
        - MYSQL_USER=$DB_USER
        - MYSQL_PASSWORD=$DB_PASSWORD
        - MYSQL_ROOT_PASSWORD=$DB_PASSWORD
    volumes:
        - ./db/:/docker-entrypoint-initdb.d
    ports:
      - 3307:3306
  app:
    depends_on:
      - mysqldb
    build: .
    restart: unless-stopped
    env_file: .env
    ports:
      - $NODE_LOCAL_PORT:3000
    environment:
      - DB_HOST=mysqldb
      - DB_USER=$DB_USER
      - DB_PASSWORD=$DB_PASSWORD
      - DB_NAME=$DB_NAME
      - DB_PORT=3306
    stdin_open: true
    tty: true

volumes: 
  db: